---
name: Bicep-Template_Build
on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  resourceGroupName: bicep
  resourceGroupLocation: norwayeast
  bicepfilePath: ./bicepfiles/main.bicep

#################################################
#                                               #        
#################    BUILD   ####################
#                                               #
#################################################

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: bicep-build-output
        uses: Azure/bicep-build-action@v1.0.1
        with:
            bicepFilePath: ${{  env.bicepfilePath }}
            outputFilePath: ./main.json

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          path: ./main.json

      - name: Azure PowerShell Action
        uses: Azure/powershell@v1
        with:
          inlineScript: ./ARM_What-If.ps1 -TestResourceGroupName  ${{ env.resourceGroupName }}
          azPSVersion: latest


#################################################
#                                               #        
#################    DEPLOY   ###################
#                                               #
#################################################

  deploy: 
   environment: prod
   runs-on: ubuntu-latest
   needs: [build]

   steps:
    - uses: actions/checkout@v3
    - name: Azure Login
      uses: Azure/login@v1.4.3
      with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Az CLI Create Resource Group
      uses: Azure/CLI@v1
      with:
        inlineScript: |
          az group create \
          --name ${{ env.resourceGroupName }} \
          --location ${{ env.resourceGroupLocation }}
    - name: Deploy bicep to Azure
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az deployment group create \
          --template-file ${{  env.bicepfilePath }} \
          --resource-group ${{ env.resourceGroupName }}